### ISSUE TITLE
Remove periods (.) from share messages

### ISSUE THREAD

**Issue by breadadams** [SaraVieira/react-social-sharing#13]
There's a `.` appended to _all_ messages, so even when there isn't a message the period gets used.

This becomes an issue for example with linkedin, where by default with "no message" you'll see the following:

![image](https://user-images.githubusercontent.com/5795227/37855890-ef6095c4-2ef1-11e8-8f7e-3f39f580dbc6.png)

Instead of what _could_ be:

![image](https://user-images.githubusercontent.com/5795227/37855902-fa1b5526-2ef1-11e8-80bf-9e6295ee8f8c.png)

**Comment by SaraVieira** [comment]
Fixed in version https://github.com/SaraVieira/react-social-sharing/releases/tag/v1.3.3 :DD
