### ISSUE TITLE
Facebook button error 

### ISSUE THREAD

**Issue by Bensigo** [SaraVieira/react-social-sharing#2]
the Facebook button does not render

**Comment by SaraVieira** [comment]
Hello!

**Comment by SaraVieira** [comment]
What do you mean? It's rendering here:https://react-social-sharing.now.sh/#/facebook

Can you show me the code?

**Comment by Bensigo** [comment]
when trying it on my react app

**Comment by SaraVieira** [comment]
Cam i see the code?

**Comment by Bensigo** [comment]
`
import { Facebook } from 'react-social-sharing';

export default () => (
   <Wrapper>
     <Footer>
          <Facebook link="#" />
      </Footer>
  </Wrapper>
)
`

**Comment by SaraVieira** [comment]
That's weird, I can make it work here: https://codesandbox.io/s/mmvlj0p3n8

Do you have Wrapper and Footer defined ?

**Comment by Bensigo** [comment]
yes

**Comment by SaraVieira** [comment]
Can you send me the full page or create a sandbox ?

**Comment by Bensigo** [comment]
ok

**Comment by Bensigo** [comment]
https://codesandbox.io/s/0mr4w4z5pp

**Comment by SaraVieira** [comment]
I can see the button: 
<img width="1257" alt="screen shot 2018-02-21 at 10 39 54" src="https://user-images.githubusercontent.com/1051509/36475741-9165204a-16f3-11e8-82e8-d9267bb16beb.png">

**Comment by Bensigo** [comment]
but not showing on my browser. I should check another browser.

**Comment by Bensigo** [comment]
working now. Thanks.
