### ISSUE TITLE
WhatsApp sharing link has a space after the 'send?text=' portion of the link

### ISSUE THREAD

**Issue by udidol** [SaraVieira/react-social-sharing#32]
In the file `consts.js`:
```
whatsapp: function whatsapp() {
    var link = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : '';
    var message = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : '';
    return 'whatsapp://send?text=' + encodeURIComponent(message) + '%20' + encodeURIComponent(link);
  },
```

For some reason, a space is added after the `send?text=` portion in the button's sharing link, before the URL. I don't use a `Message` attribute for the component, so I think that's the reason. This case should be better taken care of.

Also, this link doesn't work for desktop (WhatsApp web). You should consider changing the API link to using `https://api.whatsapp.com/send?` instead of `whatsapp://`.

**Comment by SaraVieira** [comment]
Seems this was already fixed in #34 but I never actually closed the issue

Thank you for making the issue and sorry it took an year
