### ISSUE TITLE
Add simple style support

### ISSUE THREAD

**Issue by Kikobeats** [SaraVieira/react-social-sharing#4]
Hey, @SaraVieira 

Loving this project! I would like to ask you if you are open to supporting a minimal line style, something like:

<img width="975" alt="screen shot 2018-02-22 at 00 18 26" src="https://user-images.githubusercontent.com/2096101/36511180-036325bc-1766-11e8-914e-6e857d36d98d.png">

🙂

**Comment by SaraVieira** [comment]
Hey!

Glad you enjoying the project! 😊

That looks like a super idea! I will do that tomorrow morning 👌

**Comment by SaraVieira** [comment]
Hello !

This has been added in version 1.1.0
https://github.com/SaraVieira/react-social-sharing/releases/tag/v1.1.0


Demo: https://react-social-sharing.now.sh/#/twitter

**Comment by Kikobeats** [comment]
Awesome ✨
