### ISSUE TITLE
In facebook, twitter, linkedin, view thumbnail in sharing box

### ISSUE THREAD

**Issue by magdi14** [SaraVieira/react-social-sharing#40]
Is there a way to view thumbnail or image to the post im sharing, e.g:- 
<Facebook 
   link={Link.toBeShared}
   image={Link.toAnImge} 
/>

**Comment by SaraVieira** [comment]
Hey!

Unfortunately that is not possible wit their intent API:

https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview
