### ISSUE TITLE
Unnecessary margin for icon buttons

### ISSUE THREAD

**Issue by Kikobeats** [SaraVieira/react-social-sharing#7]
Hello,

Looks something in the code is adding an unnecessary margin for buttons only based on icons:

![screen shot 2018-03-04 at 18 05 36](https://user-images.githubusercontent.com/2096101/36948159-a990a32e-1fd6-11e8-9a6e-0e9b1a951766.png)

**Comment by SaraVieira** [comment]
Interesting 🤔

CSS is a pain, I will take a look at this today
